"""Curated source families. Each family produces five distinct source/segment combinations.

Selectors match source filenames (not directory names), case-insensitively.
Lengths are editorial ceilings, not padding targets. Layers are physical texture,
not oscillator substitutes. All source choices and actual trims enter the manifest.
"""

# id, Korean label, primary selectors, secondary selectors, seconds, lowpass Hz
FAMILIES = {
    'ui': [
        ('click', '버튼 · 건조한 접점', ['Interface Percussion Snap', 'Vintage Double Click', 'USALightSwitch', 'Space Key', 'KeyPress64'], [], .13, 6500),
        ('confirm', '확인 · 유리와 접점', ['Interface Accept Glassy', 'Interface Plucks Happy', 'Kalimba'], ['KeyPress64', 'CoinTapScratch'], .45, 7200),
        ('purchase', '구매 · 동전과 승인', ['Foley Coin Flip', 'Ting Coins', 'Kalimba'], ['Interface Accept Glassy', 'Vintage Double Click'], .5, 7500),
        ('reroll', '리롤 · 카드 교체', ['Dealing 3', 'Pick Up Multiple Cards', 'Cards Dry Show Flip', 'CardMovement_09', 'Board Reset'], ['Interface Percussion Snap', 'KeyPress64'], .3, 6000),
        ('lock', '잠금 · 기계 걸쇠', ['Suitcase Being Locked', 'Latch Button', 'Case_Closed06', 'Tinkering Antique Lock', 'Screwing Lock'], [], .24, 6500),
        ('reward', '무기 보상 · 밝은 공명', ['Game Entry Happy', 'Interface Plucks Happy', 'Kalimba', 'Magic Creation'], ['Foley Coin Flip', 'Interface Accept Glassy'], .85, 7600),
        ('branch', '분기 · 마력 공명', ['Magic Creation', 'Spell Enchantment', 'energy flow, astonishment', 'Interface Arp Reveal'], ['Metal Shield Spin', 'Ting Coins'], 1.15, 7000),
        ('wave_start', '웨이브 시작 · 진입 신호', ['Interface Sci-Fi Ping', 'Tower Deploy', 'Interface Deny Low'], ['Latch Button', 'Interface Percussion Snap'], .65, 6500),
        ('wave_clear', '웨이브 완료 · 해소', ['Game Entry Happy', 'Interface Plucks Happy', 'Kalimba'], ['Magic Christmas Bells', 'Foley Coin Flip'], 1.2, 7500),
        ('stone', '마력석 · 작은 결정', ['Ting Coins', 'Kalimba', 'Interface Accept Glassy', 'Magic Christmas Bells', 'Xylophone Ringtone'], [], .17, 6500),
        ('supply', '보급 개봉 · 이중 걸쇠', ['Case_Closed06', 'Suitcase Opening', 'Latch Button', 'Opening Lid'], ['Flicking Carabiner', 'Tinkering Antique Lock', 'Handle_Movement15'], .4, 6800),
        ('result', '결과 · 짧은 팡파르', ['Game Entry Happy', 'Power Up Bright', 'Interface Plucks Happy', 'Magic Creation'], ['Kalimba', 'Magic Christmas Bells'], 2.0, 7600),
    ],
    'weapons': [
        ('mana_bolt', '마력탄 · 단단한 발사', ['CrackerPull_WithBang', 'WHIP Snap Crack', 'Combat Punch Impact'], ['ArcDesign15', 'ice, crack', 'Latch Button'], .22, 8200),
        ('piercing', '관통탄 · 빠른 파쇄', ['WHIP Snap Crack', 'CrackerPull_WithBang', 'Impact Cut Sweep'], ['ice, surface cracking', 'SWING SCRAPE', 'ArcDesign15'], .27, 8500),
        ('turret', '포탑 · 기계식 짧은 발사', ['Latch Button', 'Case_Closed06', 'Metal Old File Impact', 'Space Key'], ['CrackerPull_WithBang', 'Combat Punch Impact'], .16, 7200),
        ('slash', '검격 · 날과 접촉', ['Sword Slide Cuts', 'SWING SCRAPE', 'METAL SWING HIT', 'SWING IMPACTS'], ['Spear And Stick Impact', 'Combat Punch Impact'], .3, 8200),
        ('orbit', '표창 · 가벼운 회전', ['SWING SCRAPE', 'Sword Slide Cuts', 'Metal, Slow Whoosh'], ['Hair Scissor', 'Metal Shield Spin', 'Flicking Carabiner'], .18, 6500),
        ('mine_arm', '지뢰 · 설치 접점', ['Latch Button', 'CaseDown_Concrete', 'Screwing Lock', 'Tower Deploy'], ['USALightSwitch', 'Tinkering Antique Lock'], .3, 6500),
        ('chain', '연쇄번개 · 짧은 방전', ['ArcDesign15', 'Impact Electric Tonal', 'ArcPowerUpDesign04'], ['ice, surface cracking', 'VelcroRip29', 'Combat Punch Impact'], .32, 7200),
        ('field', '마력장 · 작동 공명', ['energy flow, astonishment', 'ArcPowerUpDesign04', 'Magic Creation'], ['Deep Fridge Hum', 'Metal Hit Thud'], .7, 6500),
        ('heavy_shot', '중화기 · 무거운 발사', ['CrackerPull_WithBang', 'powerful explosions', 'EffectiveTrailer_Booms'], ['Latch Button', 'Metal Bangs'], .4, 7500),
        ('scatter', '산탄 · 파편 발사', ['CrackerPull_WithBang', 'WHIP Snap Crack', 'Combat Punch Impact'], ['ice, block of ice', 'Glass Crystal Fragments', 'VelcroRip29'], .32, 8000),
        ('burst', '연발 · 짧은 접점', ['CrackerPull_WithBang', 'Metal Old File Impact', 'WHIP Snap Crack'], ['Counting Machine', 'Latch Button'], .15, 7600),
        ('rail', '레일 · 고속 관통', ['ArcDesign15', 'Impact Cut Sweep', 'WHIP Snap Crack'], ['Metal Scrape Low', 'ice, surface cracking'], .5, 8500),
        ('bow', '활 · 장력 해제', ['Flicking Carabiner', 'Spring Wire Impact', 'WHIP Snap Crack'], ['ClothMovement24', 'Arrow Hit Rattle'], .26, 8500),
        ('dagger', '단검 · 짧은 베기', ['Sword Slide Cuts', 'SWING SCRAPE', 'Hair Scissor'], ['SinglePats04', 'Combat Punch Impact'], .18, 8200),
        ('hammer', '둔기 · 묵직한 휘두름', ['SWING IMPACTS', 'Spear And Stick Impact', 'Metal Hit Thud'], ['ClothMovement29', 'Body 02'], .4, 6500),
        ('whip', '채찍 · 장력과 파열', ['WHIP Snap Crack', 'Metal, Slow Whoosh', 'SWING SCRAPE'], ['VelcroRip29', 'ClothMovement24'], .4, 8000),
        ('reload', '장전 · 금속 조립', ['Typewriter Carriage', 'Latch Button', 'Screwing Lock', 'Tinkering Antique Lock'], ['Case_Closed06', 'Keys In Out'], .5, 6800),
        ('deploy', '장치 배치 · 서보와 잠금', ['Tower Deploy', 'CaseDown_Concrete', 'Car Door Open'], ['Latch Button', 'Flicking Carabiner'], .7, 7000),
        ('drone', '드론 · 모터 시동', ['Quadcopter, Toy, Turn On', 'Wahl Sterling Trimmer', 'Hair Dryer'], ['Tower Deploy', 'ArcPowerUpDesign04'], .85, 6500),
        ('shield', '방패 · 전개', ['Metal Shield Spin', 'METAL SWING HIT', 'Magic Creation'], ['Latch Button', 'Spell Enchantment'], .5, 7500),
        ('dash', '돌진 · 공기와 옷감', ['ClothMovement24', 'ClothMovement29', 'SWING SCRAPE'], ['Blast Off Clean', 'Wind, Rush'], .28, 7000),
        ('charge', '충전 · 전력 상승', ['ArcPowerUpDesign04', 'energy flow, astral', 'Jump Start Drop'], ['Electricity Hum', 'Spring Wire Impact'], 1.0, 7200),
        ('throw', '투척 · 짧은 스윙', ['Cards Dry Show Flip', 'SWING SCRAPE', 'ClothMovement29'], ['Hair Scissor', 'Flicking Carabiner'], .22, 7500),
        ('device_stop', '장치 정지 · 해제', ['Latch Button', 'Cup Holder', 'LIGHTING CONTROL', 'Handle_Movement15'], ['Spring Wire Impact', 'Wahl Sterling Trimmer'], .35, 6500),
    ],
    'impacts': [
        ('hit_light', '적중 · 짧은 육체 충격', ['Combat Punch Impact', 'Body 02', 'Blood Spill Splat'], ['SinglePats04', 'Dinosaur Eating Meat'], .15, 6800),
        ('critical', '치명타 · 파열 접점', ['Gore Designed Transient', 'Combat Punch Impact', 'Body 02'], ['ice, crack', 'VelcroRip29'], .24, 7600),
        ('death', '처치 · 충격과 붕괴', ['Gore Designed Transient', 'Blood Spill Splat', 'Dinosaur Egg Hatching'], ['ice, block of ice', 'Dinosaur Eating Meat'], .35, 6800),
        ('arcane_blast', '마력 폭격 · 폭발과 결정', ['EffectiveTrailer_Booms', 'Explosion Small Blast', 'powerful explosions'], ['ice, block of ice', 'Impact Electric Tonal', 'Glass Crystal Fragments'], .85, 7600),
        ('mine_blast', '지뢰 폭발 · 금속 파편', ['Explosion Small Blast', 'EffectiveTrailer_Booms', 'powerful explosions'], ['Metal Bangs', 'CaseDown_Concrete', 'Metal Old File Impact'], .7, 7000),
        ('metal', '금속 적중', ['Metal Old File Impact', 'METAL SWING HIT', 'Metal Bangs'], ['Spring Wire Impact', 'Metal Shield Spin'], .35, 8500),
        ('armor', '갑주 충격', ['METAL SWING HIT', 'Metal Shield Spin', 'Metal Hit Thud'], ['Combat Punch Impact', 'Latch Button'], .3, 7500),
        ('wood', '목재 파손', ['Spear And Stick Impact', 'Wooden Hit', 'Board Reset'], ['Pile Of Antique Books', 'VelcroRip29'], .4, 7500),
        ('glass', '유리 파손', ['Glass Crystal Fragments', 'ice, crack', 'ice, surface cracking'], ['Metal Old File Impact', 'Ting Coins'], .55, 9000),
        ('stone', '돌 파손', ['ice, block of ice', 'CaseDown_Concrete', 'Concrete_MetalPipe02'], ['Woosh Debris', 'Metal Hit Thud'], .45, 7000),
        ('wet', '젖은 충돌', ['Blood Spill Splat', 'Water, Liquid Impact', 'Dinosaur Eating Meat'], ['Combat Punch Impact', 'Impact Water Deep'], .3, 6800),
        ('heavy_body', '대형 육체 충격', ['Body 02', 'Gore Designed Transient', 'SWING IMPACTS'], ['Metal Hit Thud', 'Dinosaur Eating Meat'], .35, 6000),
        ('electric', '전기 적중', ['ArcDesign15', 'Impact Electric Tonal', 'Buzz27'], ['Combat Punch Impact', 'ice, surface cracking'], .25, 7500),
        ('freeze', '빙결 파열', ['ice, crack', 'ice, surface cracking', 'Skill Freeze'], ['Glass Crystal Fragments', 'Combat Punch Impact'], .45, 8200),
        ('fire', '화염 충격', ['Whoosh Fire Deep', 'Explosion Small Blast', 'Fire Crackling'], ['CrackerPull_WithBang', 'Impact Cut Sweep'], .55, 7500),
        ('ricochet', '도탄 · 금속 튕김', ['Spring Wire Impact', 'Metal Old File Impact', 'Metal Shield Spin'], ['Hair Scissor', 'Flicking Carabiner'], .25, 8800),
        ('debris', '잔해 낙하', ['Woosh Debris', 'Board Reset', 'Pile Of Antique Books', 'ice, block of ice'], ['Metal, Slow Whoosh', 'Glass Crystal Fragments'], .75, 7200),
        ('collapse', '대형 붕괴', ['EffectiveTrailer_Booms', 'Metal Bangs', 'Wooden Hit'], ['ice, movement', 'Woosh Debris', 'Metal Scrape Low'], 1.3, 6500),
    ],
    'magic': [
        ('electric_cast', '전격 시전', ['ArcDesign15', 'ArcPowerUpDesign04', 'Impact Electric Tonal'], ['Spring Wire Impact', 'ice, crack'], .55, 7800),
        ('ice_cast', '냉기 시전', ['Skill Freeze', 'ice, movement', 'ice, surface cracking'], ['Glass Crystal Fragments', 'Spell Enchantment'], .75, 8500),
        ('fire_cast', '화염 시전', ['Whoosh Fire Deep', 'Fire Crackling', 'Dropping Fresh Pine'], ['Blast Off Clean', 'Combat Punch Impact'], .65, 7500),
        ('water_cast', '수류 시전', ['Water, Liquid Impact', 'Impact Water Deep', 'Putting Out Fire'], ['SWING SCRAPE', 'Magic Creation'], .65, 7200),
        ('wind_cast', '풍압 시전', ['Wind, Rush', 'Blast Off Clean', 'Impact Cut Sweep'], ['ClothMovement29', 'Metal, Slow Whoosh'], .65, 7000),
        ('shadow_cast', '그림자 시전', ['evil presence, onslaught', 'Monster Tentacle', 'Evil Spell'], ['Metal Scrape Low', 'NoiseBoxHit'], .9, 6000),
        ('holy_cast', '정화 시전', ['Spell Enchantment', 'Magic Creation', 'energy flow, astonishment'], ['Kalimba', 'Magic Christmas Bells'], .9, 7800),
        ('poison', '독성 · 기포와 침식', ['Water, Liquid Impact', 'Aquatic Creature Gurgling', 'Cartoon Bubbles'], ['VelcroRip29', 'Dinosaur Eating Meat'], .65, 6500),
        ('gate_open', '게이트 개방', ['energy flow, astral', 'Unidentified Encounter', 'Evil Spell'], ['Metal Scrape Low', 'EffectiveTrailer_Booms'], 2.0, 6500),
        ('gate_close', '게이트 수축', ['Bass Drop & Downer Medium', 'Jump Start Drop', 'Transition Braam'], ['ice, block of ice', 'Metal Hit Thud'], 1.25, 6500),
        ('teleport', '순간 이동', ['energy flow, astonishment', 'Unidentified Encounter', 'Impact Cut Sweep'], ['WHIP Snap Crack', 'Glass Crystal Fragments'], .6, 7800),
        ('heal', '회복', ['Spell Enchantment', 'Kalimba', 'Magic Creation'], ['Water, Liquid Impact', 'Ting Coins'], .8, 7200),
        ('curse', '저주 부여', ['evil presence, onslaught', 'Monster Tentacle', 'NoiseBoxHit'], ['Metal Scrape Low', 'Aquatic Creature Gurgling'], .8, 5800),
        ('barrier_break', '결계 붕괴', ['Skill Freeze', 'Glass Crystal Fragments', 'ice, block of ice'], ['ArcDesign15', 'Metal Hit Thud'], .8, 8000),
    ],
    'creatures': [
        ('player_hit', '플레이어 피격 · 명확한 충격', ['Body 02', 'Combat Punch Impact', 'SWING IMPACTS'], ['Metal Hit Thud', 'SinglePats04'], .23, 6500),
        ('small_attack', '소형 괴물 공격', ['Raptor Flair', 'Hatchling Calling', 'Violent Humanoid'], ['VelcroRip29', 'ClothMovement24'], .55, 7000),
        ('small_hurt', '소형 괴물 피격', ['Dog Shuffle', 'Violent Humanoid', 'Animal Frog'], ['Combat Punch Impact', 'Blood Spill Splat'], .4, 6500),
        ('brute_attack', '대형 괴물 공격', ['Designed Orc', 'Large Herbivore', 'T Rex'], ['Metal Hit Thud', 'Body 02'], .9, 6200),
        ('brute_hurt', '대형 괴물 피격', ['Sea Beast Creature Pain', 'Ethereal Entity Grim Pain', 'Werewolf Growl'], ['Gore Designed Transient', 'Body 02'], .75, 6000),
        ('beast', '야수 · 위협', ['Werewolf Growl', 'Raptor Flair', 'Dog Barks'], ['Dinosaur Eating Meat', 'Metal Scrape Low'], .85, 6800),
        ('insect', '곤충형 · 마찰과 떨림', ['Insectoid Creature', 'VelcroRip29', 'Dry Ice Squeak'], ['Cladding_Scratch06', 'Hair Scissor'], .65, 7500),
        ('aquatic', '수생 괴물', ['Aquatic Creature Gurgling', 'Sea Beast Creature Pain', 'Dinosaur Eating Meat'], ['Water, Liquid Impact', 'Impact Water Deep'], .9, 6500),
        ('elite_warning', '엘리트 출현 · 짧은 위협', ['HalfNotes_003', 'QuarterNotes_013', 'Cinematic Horn Braam'], ['Metal Hit Thud', 'Tower Deploy'], 1.0, 6000),
        ('boss_warning', '보스 출현 · 낮은 경고', ['Cinematic Horn Braam', 'WholeNotes_011', 'Transition Braam'], ['EffectiveTrailer_Booms', 'Large Herbivore'], 1.8, 6000),
        ('boss_roar', '보스 포효', ['T Rex', 'Large Herbivore', 'Designed Orc', 'Sea Beast Creature Pain'], ['Metal Scrape Low', 'EffectiveTrailer_Booms'], 1.6, 6500),
        ('defeat', '패배 · 무너지는 여운', ['Bass Drop & Downer Medium', 'Tone Downer', 'Interface Deny Low'], ['Metal Hit Thud', 'NoiseBoxHit'], 1.4, 5500),
    ],
    'ambience': [
        ('city_rain', '도시 · 빗소리 루프', ['Rain Medium Exterior', 'City Block Square Storm', 'Rain on Window'], ['Deep Fridge Hum'], 8.0, 10000),
        ('storm', '게이트 외곽 · 폭풍 루프', ['StormAmbience', 'Rain Light Interior', 'Heavy Rain on Window'], ['ChimneyWind05', 'Wind Strong Gusts'], 8.0, 9500),
        ('vent', '지하 시설 · 환기 루프', ['ChimneyWind05', 'Wind Whipping Constricted', 'Roomtone Space Ship'], ['Deep Fridge Hum', 'Rhythmic Electric Fridge'], 8.0, 7000),
        ('reactor', '마력 시설 · 동력 루프', ['Ship Reactor', 'Factory Loop Heavy', 'Dark Industrial Ambience'], ['Electricity Hum', 'Buzz27'], 8.0, 6500),
        ('gate_hum', '게이트 · 공간 진동 루프', ['Evil Spell Ambience', 'spellbound, evanescence', 'Mystic Forest'], ['Deep Fridge Hum', 'Metal Scrape Low'], 8.0, 6500),
        ('fire_bed', '잔불 · 연소 루프', ['Fire Crackling', 'Loop Elements Fire', 'Dropping Fresh Pine'], ['Wind Whipping Constricted'], 8.0, 9000),
        ('riverside', '강변 · 물결 루프', ['Water Ripples', 'Soft Waves Cliffs', 'Medium Waves'], ['ChimneyWind05'], 8.0, 10000),
        ('machine', '장치 · 기계 진동 루프', ['Deep Fridge Hum', 'Rhythmic Electric Fridge', 'Diesel Engine Boat'], ['Electricity Hum', 'Roomtone Space Ship'], 8.0, 7000),
        ('traffic', '도로 · 교통 배경 루프', ['Traffic Multiple Cars', 'TownDrivingAmbience', 'Freight Truck Pass'], ['Rain Medium Exterior'], 8.0, 8000),
        ('metal_room', '폐시설 · 금속 울림 루프', ['Metal Scrape Low', 'Metal Bowed Screech', 'Dark Industrial Ambience'], ['Wind Strong Metal Rattle', 'ChimneyWind05'], 8.0, 6500),
    ],
}

# Existing event IDs remain stable. New library families do not create gameplay events.
ACTIVE = {
    'purchase': ('ui/purchase', 3), 'reroll': ('ui/reroll', 3), 'lock': ('ui/lock', 3),
    'weaponPurchase': ('ui/reward', 3), 'branchChoice': ('ui/branch', 3),
    'critical': ('impacts/critical', 4), 'eliteSpawned': ('creatures/elite_warning', 2),
    'waveStarted': ('ui/wave_start', 2), 'waveCompleted': ('ui/wave_clear', 2),
    'slashAttack': ('weapons/slash', 5), 'orbitAttack': ('weapons/orbit', 4),
    'chainAttack': ('weapons/chain', 4), 'bombardAttack': ('impacts/arcane_blast', 4),
    'piercingAttack': ('weapons/piercing', 4), 'turretFired': ('weapons/turret', 4),
    'minePlaced': ('weapons/mine_arm', 3), 'mineExploded': ('impacts/mine_blast', 4),
    'fieldActivated': ('weapons/field', 3), 'weaponFired': ('weapons/mana_bolt', 5),
    'enemyHit': ('impacts/hit_light', 5), 'enemyKilled': ('impacts/death', 5),
    'magicStoneCollected': ('ui/stone', 3), 'walletSweep': ('ui/confirm', 1),
    'buttonClick': ('ui/click', 1), 'supplyLatch': ('ui/supply', 3),
    'supplyFanfare': ('ui/result', 3), 'playerHit': ('creatures/player_hit', 4),
    'bossSpawned': ('creatures/boss_warning', 2), 'stageClear': ('ui/result', 3),
    'gameOver': ('creatures/defeat', 2),
}
