import { describe, expect, it } from 'vitest';
import { createDefaultMeta } from '../state/MetaState';
import { growthCost, upgradeGrowth } from './GrowthSystem';
import { accrueOfflineRewards, claimOfflineRewards } from './OfflineRewardSystem';
import { openSupplyBox } from './SupplySystem';
import { parseSave } from '../save/migrations';
import { supplyScreen } from '../ui/MetaScreens';

describe('meta facilities',()=>{
  it('spends fragments for stored growth without changing combat stats',()=>{const meta=createDefaultMeta();meta.characters.awakener!.fragments=20;expect(growthCost(meta,'character','awakener')).toBe(20);expect(upgradeGrowth(meta,'character','awakener')).toBe(true);expect(meta.characters.awakener).toMatchObject({fragments:0,breakthrough:1});});
  it('stores blessing growth in the same five-step facility structure',()=>{const meta=createDefaultMeta();meta.blessings.cheonbuOath={unlocked:false,fragments:18,level:0};expect(growthCost(meta,'blessing','cheonbuOath')).toBe(18);expect(upgradeGrowth(meta,'blessing','cheonbuOath')).toBe(true);expect(meta.blessings.cheonbuOath).toMatchObject({unlocked:true,fragments:0,level:1});});
  it('caps offline accrual at 24 hours and claims stones once',()=>{const meta=createDefaultMeta();meta.offlineReward.lastExitAt='2026-01-01T00:00:00.000Z';expect(accrueOfflineRewards(meta,new Date('2026-01-03T00:00:00.000Z'),()=>0)).toBe(true);expect(meta.offlineReward.pendingRewards.associationCoins).toBe(144);expect(meta.offlineReward.pendingRewards.revivalStones).toEqual({low:48,mid:48,high:48});expect(claimOfflineRewards(meta,new Date('2026-01-03T00:00:01.000Z'))).toBe(true);expect(meta.wallet.associationCoins).toBe(144);expect(meta.wallet.revivalStones).toEqual({low:48,mid:48,high:48});expect(claimOfflineRewards(meta)).toBe(false);});
  it('varies coins at the same duration without rerolling pending rewards',()=>{const start='2026-01-01T00:00:00.000Z',end=new Date('2026-01-01T01:00:00.000Z');const low=createDefaultMeta(),high=createDefaultMeta();low.offlineReward.lastExitAt=start;high.offlineReward.lastExitAt=start;expect(accrueOfflineRewards(low,end,()=>0)).toBe(true);expect(accrueOfflineRewards(high,end,()=>.99)).toBe(true);expect(low.offlineReward.pendingRewards.associationCoins).toBe(6);expect(high.offlineReward.pendingRewards.associationCoins).toBe(14);expect(accrueOfflineRewards(high,end,()=>0)).toBe(false);expect(high.offlineReward.pendingRewards.associationCoins).toBe(14);});
  it('always grants coins while each bonus can independently miss',()=>{const meta=createDefaultMeta();meta.wallet.supplyTickets=1;const rewards=openSupplyBox(meta,1,()=>.99)!;expect(rewards).toEqual([{type:'associationCoins',amount:24}]);expect(meta.wallet.associationCoins).toBe(24);expect(meta.wallet.supplyTickets).toBe(0);expect(meta.supply.boxes.standard).toMatchObject({opened:1,pity:1});});
  it('makes large coin bundles rarer than small ones',()=>{const roll=(value:number)=>{const meta=createDefaultMeta();meta.wallet.supplyTickets=1;let first=true;return openSupplyBox(meta,1,()=>{if(first){first=false;return value;}return .99;})![0]!.amount;};expect([0,.6,.8,.95,.99].map(roll)).toEqual([8,10,12,16,24]);});
  it('rolls each fragment and ticket chance separately',()=>{const meta=createDefaultMeta();meta.wallet.supplyTickets=1;const values=[0,.05,0,0,.99,.99,.99];let index=0;const rewards=openSupplyBox(meta,1,()=>values[index++]??.99)!;expect(rewards.map(reward=>reward.type)).toEqual(['associationCoins','weaponFragment']);expect(meta.supply.boxes.standard?.pity).toBe(0);});
  it('rolls each revival grade separately and saves the inventory',()=>{const meta=createDefaultMeta();meta.wallet.supplyTickets=1;const rewards=openSupplyBox(meta,1,()=>0)!;expect(rewards.filter(reward=>reward.type==='revivalStone').map(reward=>reward.contentId)).toEqual(['low','mid','high']);expect(meta.wallet.revivalStones).toEqual({low:1,mid:1,high:1});});
  it('guarantees a fragment by the tenth box without one',()=>{const meta=createDefaultMeta();meta.wallet.supplyTickets=10;const rewards=openSupplyBox(meta,10,()=>.99)!;expect(rewards[0]).toEqual({type:'associationCoins',amount:240});expect(rewards.some(reward=>reward.type.endsWith('Fragment'))).toBe(true);expect(meta.supply.boxes.standard).toMatchObject({opened:10,pity:0});});
  it('renders image-led timed VFX and reward art without a close instruction',()=>{const html=supplyScreen(createDefaultMeta(),[{type:'associationCoins',amount:20}]);expect(html).toContain('supply-stage');expect(html).toContain('crate-closed');expect(html).toContain('crate-wide');expect(html).toContain('crate-transition-flash');expect(html).toContain('supply-burst-image');expect(html).toContain('supply-result-backplate');expect(html).toContain('supply-reward-art');expect(html).toContain('협회 코인');expect(html).not.toContain('눌러서 닫기');expect(html).not.toContain('supply-platform-image');});
  it('migrates v9 offline rewards into the structured v12 state',()=>{const meta=createDefaultMeta();const legacy={...meta,offlineReward:{lastExitAt:'',lastClaimedAt:'',pendingRewards:{associationCoins:3}}};const save=parseSave(JSON.stringify({saveVersion:9,meta:legacy}));expect(save.saveVersion).toBe(12);expect(save.meta.offlineReward.pendingRewards).toMatchObject({associationCoins:3,supplyTickets:0,revivalStones:{low:0,mid:0,high:0}});});
});
