import { characters } from '../data/characters';
import { images, type ImageId } from '../data/images';
import { META_GROWTH_CONFIG, SUPPLY_BOX_CONFIG } from '../data/metaFacilities';
import { metaUpgrades } from '../data/meta';
import { dangunBlessings } from '../data/weeklyGate';
import { weapons } from '../data/weapons';
import { REVIVAL_STONES, REVIVAL_STONE_GRADES, type RevivalStoneGrade } from '../data/revivalStones';
import { growthCost } from '../meta/GrowthSystem';
import { getUpgradeCost } from '../meta/progression';
import { hasOfflineRewards } from '../meta/OfflineRewardSystem';
import type { MetaReward } from '../meta/SupplySystem';
import type { MetaState } from '../state/MetaState';
import { button, escapeHtml } from './helpers';
import { weaponArt, weaponDetailArt } from './InventoryArt';
import { lobbyReturnButton } from './LobbyNavigation';

export interface GrowthViewState { tab:'character'|'weapon'|'blessing'; selectedId:string }
const facility=(kind:string,image:ImageId,eyebrow:string,title:string,body:string)=>`<section class="meta-facility ${kind}" style="--facility-bg:url('${images[image].url}')"><div class="facility-shade"></div><header>${lobbyReturnButton()}<span><small>${eyebrow}</small><h1>${title}</h1></span></header>${body}</section>`;
const progressDots=(level:number,max:number)=>`<div class="growth-dots" aria-label="성장 ${level}/${max}">${Array.from({length:max},(_,i)=>`<i class="${i<level?'active':''}"></i>`).join('')}</div>`;

export function growthScreen(meta:MetaState,view:GrowthViewState):string {
  const ids=view.tab==='character'?Object.keys(characters):view.tab==='weapon'?Object.keys(weapons):Object.keys(dangunBlessings);
  const selected=ids.includes(view.selectedId)?view.selectedId:ids[0]??'';
  const info=(id:string)=>view.tab==='character'?characters[id]:view.tab==='weapon'?weapons[id]:dangunBlessings[id];
  const progressFor=(id:string)=>view.tab==='character'?meta.characters[id]??{unlocked:false,fragments:0,breakthrough:0}:view.tab==='weapon'?meta.sharedWeapons[id]??{unlocked:false,fragments:0,level:0}:meta.blessings[id]??{unlocked:false,fragments:0,level:0};
  const art=(id:string)=>view.tab==='character'?`<img src="${images[characters[id]?.portraitSprite??characters[id]?.visual.sprite??'player'].url}" alt="">`:view.tab==='weapon'?weaponDetailArt(id):`<img src="${images[dangunBlessings[id]?.image??'blessingBlade'].url}" alt="">`;
  const list=ids.map(id=>{const def=info(id),progress=progressFor(id);return `<button class="facility-list-item ${id===selected?'selected':''} ${progress.unlocked?'':'locked'}" data-action="growth-select:${view.tab},${id}">${art(id)}<span><b>${escapeHtml(def?.name??id)}</b><small>${progress.unlocked?'성장 가능':'잠김'}</small></span></button>`}).join('');
  const progress=progressFor(selected),level=view.tab==='character'&&'breakthrough'in progress?progress.breakthrough:'level'in progress?progress.level:0;
  const cost=growthCost(meta,view.tab,selected),max=level>=META_GROWTH_CONFIG.maxLevel,def=info(selected);
  const typeLabel=view.tab==='character'?'AWAKENER':view.tab==='weapon'?'SHARED WEAPON':'DANGUN BLESSING';
  const canGrow=progress.fragments>=cost&&(view.tab==='blessing'||progress.unlocked);
  const growthLabel=view.tab==='blessing'&&!progress.unlocked?'축복 해금':max?'최대 성장':'성장';
  return facility('growth-facility','metaGrowthLab','FUTURE STRATEGY SUPPORT','미래전략지원실',`<nav class="facility-tabs"><button data-action="growth-tab:character" class="${view.tab==='character'?'active':''}">캐릭터</button><button data-action="growth-tab:weapon" class="${view.tab==='weapon'?'active':''}">공용 무기</button><button data-action="growth-tab:blessing" class="${view.tab==='blessing'?'active':''}">단군의 축복</button></nav><main class="facility-workspace"><aside class="facility-list"><div class="facility-list-grid" role="list" aria-label="${view.tab==='character'?'캐릭터':view.tab==='weapon'?'공용 무기':'단군의 축복'} 목록">${list}</div></aside><div class="growth-subject">${art(selected)}<small>${typeLabel}</small><h2>${escapeHtml(def?.name??selected)}</h2></div><aside class="facility-control"><span class="status-chip">${view.tab==='blessing'?(progress.unlocked?'출동 선택 가능':'조각 해금'):'효과 연결 예정'}</span><h2>성장 단계</h2>${progressDots(level,META_GROWTH_CONFIG.maxLevel)}<div class="resource-line"><span>보유 조각</span><b>${progress.fragments}</b></div><div class="resource-line"><span>필요 조각</span><b>${max?'완료':Number.isFinite(cost)?cost:'-'}</b></div>${button(`growth-upgrade:${view.tab},${selected}`,growthLabel,'primary',max||!canGrow?'disabled':'')}<small class="facility-note">${view.tab==='blessing'?'해금한 축복은 출동 전 하나를 선택합니다.':'성장 기록은 보존되며 전투 효과는 추후 연결됩니다.'}</small></aside></main>`);
}

export function associationScreen(meta:MetaState):string {
  const cards=Object.values(metaUpgrades).map(def=>{
    const level=meta.association.upgrades[def.id]??0,cost=getUpgradeCost(meta,def.id);
    const maxed=level>=def.maxLevel||!Number.isFinite(cost),permit=def.effect.type==='unlock';
    return `<article class="association-offer ${maxed?'completed':''}"><div class="association-offer-head"><img src="${images[permit?'lobbyArchive':'lobbyFutureStrategy'].url}" alt=""><span><h2>${escapeHtml(def.name)}</h2></span><b class="association-level">${maxed?def.maxLevel:level}<small> / ${def.maxLevel}</small></b></div><p>${escapeHtml(def.description)}</p>${progressDots(maxed?def.maxLevel:level,def.maxLevel)}<button type="button" class="association-purchase" data-action="buy:${def.id}" ${maxed||meta.wallet.associationCoins<cost?'disabled':''}><span>${maxed?'지원 완료':permit?'해금':'강화'}</span>${maxed?'':`<span class="association-price"><img src="${images.associationCoin.url}" alt="협회 코인"><b>${cost.toLocaleString()}</b></span>`}</button></article>`;
  }).join('');
  return facility('association-facility','metaAssociationOffice','AWAKENER ASSOCIATION','협회',`<main class="association-layout"><aside class="association-desk"><div class="association-emblem"><img src="${images.lobbyAssociation.url}" alt="각성자 협회 인장"></div><h2>기록은 남고,<br>전력은 축적됩니다.</h2><div class="association-wallet"><img src="${images.associationCoin.url}" alt=""><span>보유 협회 코인<b>${meta.wallet.associationCoins.toLocaleString()}</b></span></div></aside><section class="association-services"><header><h2>협회 지원</h2></header><div class="association-counter">${cards}</div></section></main>`);
}

function pendingRows(meta:MetaState):string {const p=meta.offlineReward.pendingRewards;const rows:[string,string,number][]=[];if(p.associationCoins)rows.push(['협회 코인',images.associationCoin.url,p.associationCoins]);if(p.supplyTickets)rows.push(['보급권',images.supplyTicket.url,p.supplyTickets]);for(const grade of REVIVAL_STONE_GRADES)if(p.revivalStones[grade])rows.push([REVIVAL_STONES[grade].name,images[REVIVAL_STONES[grade].image].url,p.revivalStones[grade]]);for(const [id,n] of Object.entries(p.characterFragments)){if(n)rows.push([`${characters[id]?.name??id} 조각`,images[characters[id]?.portraitSprite??characters[id]?.visual.sprite??'player'].url,n]);}for(const [id,n] of Object.entries(p.weaponFragments)){if(n)rows.push([`${weapons[id]?.name??id} 조각`,images.lobbyWeapons.url,n]);}for(const [id,n] of Object.entries(p.blessingFragments)){if(n)rows.push([`${dangunBlessings[id]?.name??id} 조각`,images[dangunBlessings[id]?.image??'blessingBlade'].url,n]);}return rows.length?rows.map(([name,art,n])=>`<li><img src="${art}" alt=""><span>${escapeHtml(name)}</span><b>+${n}</b></li>`).join(''):'<li class="empty"><img src="'+images.lobbyRecoveryUnit.url+'" alt=""><span>회수품 대기 중</span></li>';}
export const offlineClaimVisual=()=>`<div class="offline-transfer" aria-label="정산 완료"><img src="${images.associationCoin.url}" alt=""><img src="${images.supplyTicket.url}" alt=""><img src="${images.blessingCheonbuOath.url}" alt=""><strong>정산 완료</strong></div>`;
export const offlineEmptyRows=()=>`<li class="empty"><img src="${images.lobbyRecoveryUnit.url}" alt=""><span>회수품 대기 중</span></li>`;
export const offlineEmptyArt=()=>`<img class="manifest-empty-art" src="${images.lobbyRecoveryUnit.url}" alt="">`;
export function offlineScreen(meta:MetaState):string {const has=hasOfflineRewards(meta.offlineReward.pendingRewards);return facility('offline-facility','metaOfflineTerminal','RECOVERY DESK','오프라인 보상',`<main class="offline-console"><div class="offline-recovery ${has?'ready':''}"><span class="recovery-scan"></span><img src="${images.lobbyRecoveryUnit.url}" alt=""><i></i><span class="recovery-caption"><small>FIELD RECOVERY UNIT</small><b>${has?'회수품 도착':'회수 대기'}</b></span></div><div class="offline-manifest"><header><img src="${images.lobbyArchive.url}" alt=""><span><small>RETURN MANIFEST</small><h2>회수 기록</h2></span><b class="manifest-status ${has?'ready':''}">${has?'정산 가능':'대기 중'}</b></header><ul>${pendingRows(meta)}</ul>${has?'':offlineEmptyArt()}${button('offline-claim','회수품 수령 →','primary',has?'':'disabled')}</div></main>`)}

const rewardName=(reward:MetaReward):string=>reward.type==='associationCoins'?'협회 코인':reward.type==='supplyTicket'?'보급권':reward.type==='revivalStone'?REVIVAL_STONES[reward.contentId as RevivalStoneGrade]?.name??'생환석':reward.type==='characterFragment'?`${characters[reward.contentId??'']?.name??''} 조각`:reward.type==='weaponFragment'?`${weapons[reward.contentId??'']?.name??''} 조각`:`${dangunBlessings[reward.contentId??'']?.name??''} 조각`;
const rewardArt=(reward:MetaReward):string=>{if(reward.type==='associationCoins')return `<img src="${images.associationCoin.url}" alt="협회 코인">`;if(reward.type==='supplyTicket')return `<img src="${images.supplyTicket.url}" alt="보급권">`;if(reward.type==='revivalStone'){const stone=REVIVAL_STONES[reward.contentId as RevivalStoneGrade];return `<img src="${images[stone?.image??'revivalStoneLow'].url}" alt="">`;}if(reward.type==='characterFragment'){const character=characters[reward.contentId??''];return `<img src="${images[character?.portraitSprite??character?.visual.sprite??'player'].url}" alt="">`;}if(reward.type==='weaponFragment')return weaponArt(reward.contentId??'');const blessing=dangunBlessings[reward.contentId??''];return `<img src="${images[blessing?.image??'blessingBlade'].url}" alt="">`;};
export function supplyScreen(meta:MetaState,results:readonly MetaReward[]):string {const state=meta.supply.boxes[SUPPLY_BOX_CONFIG.id]??{opened:0,pity:0};const particles=Array.from({length:18},(_,i)=>`<i style="--p:${i}"></i>`).join('');return facility('supply-facility','metaSupplyVault','SUPPLY VAULT','보급 상자',`<div class="facility-balance ticket"><img src="${images.supplyTicket.url}" alt=""><span>보급권</span><b>${meta.wallet.supplyTickets}</b></div><main class="supply-console"><div class="supply-machine"><img src="${images.lobbySupplyVault.url}" alt=""><span>누적 개봉 ${state.opened}</span><small>조각 보장까지 ${Math.max(1,SUPPLY_BOX_CONFIG.pityLimit-state.pity)}회</small></div><div class="supply-controls"><h2>표준 보급 상자</h2><p>협회 코인과 성장 조각, 보급권을 획득합니다.</p><div>${button('supply-open:1','1회 개봉','primary',meta.wallet.supplyTickets<1?'disabled':'')}${button('supply-open:10','10회 개봉','secondary',meta.wallet.supplyTickets<10?'disabled':'')}</div></div></main>${results.length?`<button class="supply-results" data-action="supply-dismiss" aria-label="보급 결과 닫기"><span class="supply-stage"><img class="supply-chamber" src="${images.metaSupplyVault.url}" alt=""><i class="supply-backlight"></i><img class="supply-burst-image burst-a" src="${images.supplyOpeningBurst.url}" alt=""><img class="supply-burst-image burst-b" src="${images.supplyOpeningBurst.url}" alt=""><span class="supply-crate"><img class="crate-pose crate-closed" src="${images.lobbySupply.url}" alt=""><img class="crate-pose crate-wide" src="${images.lobbySupplyWide.url}" alt=""><i class="crate-transition-flash"></i><i class="crate-lock left"></i><i class="crate-lock right"></i><i class="crate-core"></i></span><span class="supply-vapor"><i></i><i></i><i></i></span><span class="supply-particles">${particles}</span></span><span class="supply-reveal"><img class="supply-result-backplate" src="${images.supplyResultBackplate.url}" alt=""><span class="supply-result-heading"><img src="${images.lobbySupplyWide.url}" alt=""><span><em>ASSOCIATION SUPPLY</em><strong>보급 결과</strong></span><b>${results.length}건 확보</b></span><span class="supply-reward-grid">${results.map((r,i)=>`<i class="${r.type}" style="--p:${i}"><span class="supply-reward-art">${rewardArt(r)}</span><b>${escapeHtml(rewardName(r))}</b><strong>+${r.amount}</strong></i>`).join('')}</span></span></button>`:''}`)}




