import { calculateStageReward } from '../meta/StageReward';
import { images } from '../data/images';
import type { MetaState } from '../state/MetaState';
import type { RunState } from '../state/RunState';
import { button, formatTime } from './helpers';
import { lobbyReturnButton } from './LobbyNavigation';

export type Screen = 'lobby' | 'gateMap' | 'gateDepth' | 'gateCharacter' | 'gateWeapon' | 'gateBlessing' | 'gateConfirm'
  | 'growth' | 'association' | 'offline' | 'supply' | 'archive' | 'settings'
  | 'waveActive' | 'paused' | 'revivalChoice' | 'shop' | 'postWave' | 'result';
const back=()=>lobbyReturnButton();
export function settingsScreen(meta:MetaState):string{const s=meta.settings;const slider=(id:string,label:string,value:number)=>`<label class="setting-row"><span>${label}</span><div class="volume-control"><input aria-label="${label}" type="range" min="0" max="1" step="0.05" value="${value}" data-setting="${id}"><output>${Math.round(value*100)}%</output></div></label>`;return `<section class="settings-facility" style="--settings-art:url('${images.lobbySettings.url}')"><header>${back()}<span><small>OPERATION CONTROL</small><h1>설정</h1></span></header><main class="settings-console"><aside class="settings-hero"><img src="${images.lobbySettings.url}" alt=""><small>SYSTEM STATUS</small><i></i></aside><div class="settings-panels"><section class="settings-card audio-board"><small>AUDIO MIXER</small><h2>음향 제어</h2>${slider('masterVolume','전체 음량',s.masterVolume)}${slider('musicVolume','음악',s.musicVolume)}${slider('combatVolume','전투 효과음',s.combatVolume)}${slider('uiVolume','UI 효과음',s.uiVolume)}</section><section class="settings-card switch-board"><small>FIELD SYSTEM</small><h2>작전 장치</h2><label class="setting-row"><span>모든 소리 음소거</span><input type="checkbox" data-setting="muted" ${s.muted?'checked':''}></label><label class="setting-row"><span>고해상도 화면</span><input type="checkbox" data-setting="highResolution" ${s.highResolution?'checked':''}></label><label class="setting-row"><span>개발자 모드</span><input type="checkbox" data-setting="developerMode" ${s.developerMode?'checked':''}></label><button class="mobile-fullscreen-button" data-action="fullscreen">화면 채우기</button></section><section class="settings-card data-board"><small>SECURE ARCHIVE</small><h2>진행 기록과 백업</h2><div class="button-row">${button('export','JSON 백업 내보내기','secondary')}<label class="button secondary file-button">백업 가져오기<input id="save-file" type="file" accept="application/json,.json"></label></div><div class="danger-zone">${button('reset','저장 데이터 초기화','danger')}<small>모든 영구 진행 기록을 지웁니다.</small></div><div class="settings-account-slot"><h3>계정</h3></div></section></div></main></section>`}
export function pauseScreen():string{return `<section class="modal pause-modal"><span class="phase-symbol">Ⅱ</span><h1>일시정지</h1><div class="stack">${button('resume','전투 계속','primary')}${button('end-run','출동 종료','secondary')}</div></section>`}
export function resultScreen(run:RunState):string{const clear=run.phase==='stageClear',reward=run.reward??calculateStageReward(run),deferred=run.walletBonusRemaining+run.walletStoredThisRun+run.pickups.reduce((sum,p)=>sum+p.value,0);return `<section class="modal result-modal"><span class="eyebrow">GATE DEPTH ${run.gateDepth}</span><img class="result-art ${clear?'sealed':''}" src="${images.gate.url}" alt=""><h1>${clear?'게이트 봉쇄 완료':'출동 종료'}</h1><div class="result-grid"><div><small>완료 Wave</small><strong>${reward.completedWaves}/${run.totalWaves}</strong></div><div><small>처치</small><strong>${run.kills}</strong></div><div><small>전투 시간</small><strong>${formatTime(run.stageCombatTime)}</strong></div><div><small>협회 코인</small><strong>+${Math.floor(run.earnedAssociationCoins)}</strong></div><div><small>현장 회수</small><strong>${Math.floor(run.collectedMagicStone)} ◇</strong></div><div><small>미회수</small><strong>${Math.floor(deferred)} ◇</strong></div></div><div class="stack">${button('association','협회','primary')}${button('gateMap','다시 출동','secondary')}${button('lobby','로비','quiet')}</div></section>`}
export function postWaveScreen(run:RunState):string{return `<section class="modal post-wave-modal"><span class="phase-pill">WAVE ${run.currentWave}</span><h1>교전 종료</h1><div class="post-metrics"><div><strong>${run.kills-run.waveStartKills}</strong><small>처치</small></div><div><strong>${formatTime(run.waveElapsedTime)}</strong><small>전투 시간</small></div></div>${button('post-continue','편의점 →','primary')}</section>`}
export { shopScreen } from './ShopScreen';
