import {describe,expect,it} from 'vitest';
import {Simulation} from '../core/Simulation';
import {createDefaultMeta} from '../state/MetaState';
import {weapons} from '../data/weapons';
import {SHOP_CONFIG} from '../data/shopConfig';
import {buyItem,buyWeapon,eligibleWeaponOffers,itemRerollCost,rerollItems,rerollWeapons,toggleItemLock,toggleWeaponLock,weaponPrice,weaponRerollCost} from './ShopSystem';

const make=(random=()=>0.4)=>{const sim=new Simulation('awakener','seoul',createDefaultMeta(),random);sim.completeWave();sim.continuePostWave();return sim;};

describe('combined weapon and item shop',()=>{
 it('opens four independent slots for each catalog',()=>{const run=make().state;expect(run.shop.itemStock.slots).toHaveLength(4);expect(run.shop.weaponStock.slots).toHaveLength(4);expect(run.phase).toBe('shop');});
 it('uses fixed data-driven weapon prices',()=>{expect(weaponPrice({weaponId:'manaSword',targetLevel:1})).toBe(36);expect(weaponPrice({weaponId:'autoTurret',targetLevel:1})).toBe(44);expect([2,3,4,5,6,7,8,9,10].map(level=>weaponPrice({weaponId:'manaBolt',targetLevel:level}))).toEqual([14,18,23,28,33,38,43,48,54]);});
 it('purchases a new weapon, prevents duplicates and spends only Run currency',()=>{const sim=make(),run=sim.state;const index=run.shop.weaponStock.slots.findIndex(slot=>slot.weaponId&&slot.targetLevel===1);expect(index).toBeGreaterThanOrEqual(0);const offer={...run.shop.weaponStock.slots[index]!};run.runCurrency=100;expect(buyWeapon(run,index)).toBe(true);expect(run.runCurrency).toBe(100-weaponPrice({weaponId:offer.weaponId!,targetLevel:1}));expect(run.ownedWeapons.filter(w=>w.id===offer.weaponId)).toHaveLength(1);expect(eligibleWeaponOffers(run).filter(o=>o.weaponId===offer.weaponId&&o.targetLevel===1)).toEqual([]);});
 it('purchases an upgrade and requires the free branch choice at Lv.5',()=>{const sim=make(),run=sim.state;run.runCurrency=500;const weapon=run.ownedWeapons[0]!;weapon.level=4;run.shop.weaponStock.slots[0]={weaponId:weapon.id,targetLevel:5,locked:false};expect(sim.buyShopWeapon(0)).toBe(true);expect(weapon.level).toBe(5);expect(run.pendingBranchWeaponId).toBe(weapon.id);expect(sim.nextWave()).toBe(false);expect(sim.chooseBranch('A')).toBe(true);expect(weapon.branchId).toBe('A');expect(sim.nextWave()).toBe(true);});
 it('rerolls and locks item and weapon stocks independently',()=>{const sim=make(),run=sim.state;run.runCurrency=500;const item=run.shop.itemStock.slots[0]!.itemId,weapon=run.shop.weaponStock.slots[0]!.weaponId;toggleItemLock(run,0);toggleWeaponLock(run,0);expect(itemRerollCost(run)).toBe(5);expect(weaponRerollCost(run)).toBe(6);expect(rerollItems(run,()=>0.8)).toBe(true);expect(run.shop.itemStock.slots[0]!.itemId).toBe(item);expect(run.shop.weaponStock.slots[0]!.weaponId).toBe(weapon);expect(run.shop.weaponStock.rerolls).toBe(0);expect(rerollWeapons(run,()=>0.7)).toBe(true);expect(run.shop.weaponStock.slots[0]!.weaponId).toBe(weapon);expect(run.shop.itemStock.rerolls).toBe(1);expect(itemRerollCost(run)).toBe(10);expect(weaponRerollCost(run)).toBe(12);});
 it('preserves locks and cumulative reroll costs into the next Wave shop',()=>{const sim=make(),run=sim.state;run.runCurrency=500;toggleItemLock(run,0);toggleWeaponLock(run,0);rerollItems(run,()=>0.6);rerollWeapons(run,()=>0.6);const item=run.shop.itemStock.slots[0]!.itemId,weapon=run.shop.weaponStock.slots[0]!.weaponId;sim.nextWave();sim.completeWave();sim.continuePostWave();expect(run.shop.itemStock.slots[0]).toMatchObject({itemId:item,locked:true});expect(run.shop.weaponStock.slots[0]).toMatchObject({weaponId:weapon,locked:true});expect(itemRerollCost(run)).toBe(SHOP_CONFIG.itemRerollBase+SHOP_CONFIG.itemRerollStep);expect(weaponRerollCost(run)).toBe(SHOP_CONFIG.weaponRerollBase+SHOP_CONFIG.weaponRerollStep);});
 it('keeps item purchases and max stacks working',()=>{const run=make().state;run.shop.itemStock.slots[0]={itemId:'energyDrink',locked:false};run.runCurrency=20;expect(buyItem(run,0)).toBe(true);expect(run.runCurrency).toBe(8);expect(run.calculatedStats.attackSpeed).toBeCloseTo(1.08);});
 it('offers only upgrades when six slots are occupied and excludes maxed weapons',()=>{const run=make().state;run.ownedWeapons=Object.values(weapons).slice(0,6).map(w=>({id:w.id,level:w.maxLevel,cooldownRemaining:0,branchId:'A'}));expect(eligibleWeaponOffers(run)).toEqual([]);});
});
